version: '3'
services:
  bms-api:
    build:
      context: ./docker/dockerfile
      dockerfile: app
      args:
      - 'WWWUSER=${WWWUSER}'
    image: fms/app
    container_name: bms-api
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bms
    depends_on:
      - bms-mysql

  bms-gateway:
    image: nginx:alpine
    container_name: bms-gateway
    restart: unless-stopped
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./:/var/www
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bms
    depends_on:
      - bms-api

  bms-mysql:
    image: 'mysql:8.0'
    container_name: bms-mysql
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'bmsmysql:/var/lib/mysql'
    networks:
      - bms

networks:
    bms:
        driver: bridge
volumes:
    bmsmysql:
        driver: local
